sudo: false
language: java
before_install:
- "./gradlew -version"
install: "./gradlew assemble"
before_script:
- mysql -u root -v < dbfit-java/mysql/src/integration-test/resources/create-db-mysql.sql
script: "./gradlew clean travisbuild"
jdk:
- oraclejdk7
- oraclejdk8
after_success:
- "./gradlew bundle"
addons:
  artifacts:
    paths:
    - zips/
    target_paths: artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
    s3_region: us-east-1
env:
  matrix:
    secure: gOEl7TFI3RH0cMkSNOXeSwC0ZCF60/JSftuTK0Y7UZtSS4yEYkn4o2RX/PO3I+3kQdpkbx9pe+lnd1+C1to1QJqd4AhOGwoy/7KvTE+qCP0bdOLSWUbWJ92SmI/ZPijnODfcFWWkCDIhQBK0SEinVokjD5PPobDwGMosDMS2Qzo=
